apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sql-provider
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: platform
  source:
    repoURL: https://github.com/ronsevetoci/argocd.git
    targetRevision: main
    path: manifests/crossplane-providers/providers/sql
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-systemdasd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # - CreateNamespace=true
      # mysql resources are often CRDs; this avoids early dry-run failures:
      - SkipDryRunOnMissingResource=true
