apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kro
    repoURL: registry.k8s.io/kro/charts
    targetRevision: 0.8.1
  destination:
    namespace: kro
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true