apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 50-gateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: platform
  source:
    repoURL: oci://docker.io/envoyproxy
    chart: gateway-crds-helm
    targetRevision: v1.6.3
    helm:
      releaseName: eg-crds
      values: "crds:\n  gatewayAPI:\n    enabled: true\n    channel: standard\n  envoyGateway:\n\
        \    enabled: true\n"
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
