apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: demo-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: LISTEN_ADDR
              value: ":8080"
            - name: SESSION_TTL
              value: {{ .Values.app.sessionTTL | quote }}
            - name: MAX_BODY_BYTES
              value: {{ .Values.app.maxBodyBytes | quote }}
            - name: VERBOSE_BY_DEFAULT
              value: {{ .Values.app.verboseByDefault | quote }}
            - name: REQUIRE_JSON
              value: {{ .Values.app.requireJSON | quote }}

            # ---- Redis host/port/password from secret ----
            - name: REDIS_ADDR
              value: "$(REDIS_HOST):$(REDIS_PORT)"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.connections.redis.secretName }}
                  key: {{ .Values.connections.redis.hostKey }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.connections.redis.secretName }}
                  key: {{ .Values.connections.redis.passwordKey }}
                  optional: true
          command: ["/demo-api"]
          args: []
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
