apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: demo-api
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.parentGatewayName }}
      namespace: {{ .Values.gateway.parentGatewayNamespace }}
  rules:
    - backendRefs:
        - name: demo-api
          port: {{ .Values.service.port }}
