apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-api.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "demo-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
