apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 60-envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: platform
  source:
    repoURL: REPO_URL
    targetRevision: main
    path: apps/60-envoy-gateway
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
