apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 60-envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '60'
spec:
  project: platform
  source:
    repoURL: oci://docker.io/envoyproxy/gateway-helm 
    chart: gateway-helm
    targetRevision: v0.0.0-latest
    helm:
      releaseName: envoy-proxy
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
