apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 60-envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '60'
spec:
  project: platform
  source:
    repoURL: oci://docker.io/envoyproxy
    chart: gateway-helm
    targetRevision: v1.6.3
    helm:
      releaseName: eg
      skipCrds: true
      values: "deployment:\n  envoyGateway:\n    nodeSelector:\n      name: core\n\
        \n# Optional: run multiple replicas (needs PDB/HA considerations)\n# deployment:\n\
        #   replicas: 2\n"
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
