apiVersion: oci.oraclecloud.com/v1alpha1
kind: OCINodeClass
metadata:
  name: oci-node
spec:
  shapeConfigs:
    - ocpus: 1
      memoryInGbs: 8
  volumeConfig:
    bootVolumeConfig:
      sizeInGBs: 100
      vpusPerGB: 10
      pvEncryptionInTransit: true
      imageConfig:
        imageType: OKEImage
        imageId: "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaark6eswpvweu4epvsu4hftwbtzcpxaeat6i4ap2r7jv6zborelpaq"
#        imageFilter:
#          osFilter: OracleLinux
#          osVersionFilter: "8"  #refer to ImageConfig section above to find an compatible OKEImage
#          freeformTags:
#            base_image_name: Oracle-Linux-8.10-2025.09.16-0
#            base_image_ocid: ocid1.image.oc1.phx.aaaaaaaaodf4rssimwiwwrc7znhe3vuyt6yxb7ducuxgyft4uqa4brodw4pa
#            k8s_version: v1.33.1
#            release_number: a2e20de8d41
  networkConfig:
    primaryVnicConfig:
      subnetConfig:
        subnetId: "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaadg2a5ghugyjctvblad23r735r7fn33wofakwpiqvwftemsgtobra"
      networkSecurityGroupConfigs:
        - networkSecurityGroupId: "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaynuhfktcsud4cbaykho57u6svxwwicd5ilrixc67n5q3hu4k655q"
    secondaryVnicConfigs:
      - subnetConfig:
          subnetId: "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaacn6qhvhx5q32zeguf6uyehx3kt66o6in4f5fmkejt5n57idtac5a"
        networkSecurityGroupConfigs:
          - networkSecurityGroupId: "ocid1.networksecuritygroup.oc1.eu-frankfurt-1.aaaaaaaaaop7xrbqqzr36fr77flojwiu7locutszbueioyqits5zay4k2fxa"
        ipCount: 16
  kubeletConfig:
    maxPods: 30
    evictionMaxPodGracePeriod: 15