apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-api-config
  namespace: {{ .Values.namespace }}
data:
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  MYSQL_HOST: {{ .Values.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.mysql.port | quote }}
  MYSQL_DB: {{ .Values.mysql.database | quote }}
