apiVersion: v1
      kind: Secret
      metadata:
        name: mysql-db-admin-secret
        namespace: {{ .Values.namespace }}
      type: Opaque
      data:
        pass: "MTIzNDU2"     #encoded secret