apiVersion: mysql.oci.upbound.io/v1alpha1
kind: MysqlDbSystem
metadata:
  labels:
    testing.upbound.io/example-name: mysqldbsystem_label_1
  name: mysqldbsystem1
spec:
  forProvider:
    # Refer to following terraform example for brief resource fields
    # https://registry.terraform.io/providers/oracle/oci/7.27.0/docs/resources/mysql_mysql_db_system
    availabilityDomain: "Vihs:EU-FRANKFURT-1-AD-1"
    compartmentId: "ocid1.compartment.oc1..aaaaaaaayevnkjfyjb6nglndfrvgoy7hciclgf4kq7ioulokey7xfpixjhxa"
    shapeName: "MySQL.2"
    displayName: mysqldbsystem1        #Optional_field
    subnetId: "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaadg2a5ghugyjctvblad23r735r7fn33wofakwpiqvwftemsgtobra"
    adminPasswordSecretRef:
      key: MYSQL_PASSWORD            # Key within the Secret
      name: {{ .Values.dbSecret.name }}    # Secret name
      namespace: {{ .Values.namespace }}    # Secret namespace
    adminUsername: admin        # Administrative username
    writeConnectionSecretToRef:
      name: mysqldbsystem1-conn
      namespace: {{ .Values.namespace }}