apiVersion: redis.oci.upbound.io/v1alpha1
kind: RedisCluster
metadata:
  labels:
    testing.upbound.io/example-name: rediscluster_label_1
  name: rediscluster1
spec:
  publishConnectionDetailsTo:
    name: {{ .Values.connections.redis.secretName }}
    namespace: {{ .Values.namespace }}
  forProvider:
    # Refer to following terraform example for brief resource fields
    # https://registry.terraform.io/providers/oracle/oci/7.27.0/docs/resources/redis_redis_cluster
    compartmentId: "ocid1.compartment.oc1..aaaaaaaayevnkjfyjb6nglndfrvgoy7hciclgf4kq7ioulokey7xfpixjhxa"
    displayName: rediscluster1
    nodeCount: 1
    nodeMemoryInGbs: 2
    softwareVersion: REDIS_7_0
    subnetId: "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaadg2a5ghugyjctvblad23r735r7fn33wofakwpiqvwftemsgtobra"