apiVersion: mysql.oci.upbound.io/v1alpha1
kind: MysqlDbSystem
metadata:
  labels:
    testing.upbound.io/example-name: mysqldbsystem_label_1
  name: mysqldbsystem1
spec:
  forProvider:
    # Refer to following terraform example for brief resource fields
    # https://registry.terraform.io/providers/oracle/oci/7.27.0/docs/resources/mysql_mysql_db_system
    availabilityDomain: "EU-FRANKFURT-1-AD-1"
    compartmentId: "ocid1.compartment.oc1..aaaaaaaayevnkjfyjb6nglndfrvgoy7hciclgf4kq7ioulokey7xfpixjhxa"
    shapeName: "MySQL.2"
    displayName: mysqldbsystem1        #Optional_field
    subnetId: "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaadg2a5ghugyjctvblad23r735r7fn33wofakwpiqvwftemsgtobra"
    adminPasswordSecretRef:
      # Prerequisite: Before creating the MysqlDbSystem resource, copy the following Secret manifest
      # into a separate YAML file (e.g., mysql-db-admin-secret.yaml) and apply it using:
      # kubectl apply -f mysql-db-admin-secret.yaml
      #
      # Example:
      #apiVersion: v1
      #kind: Secret
      #metadata:
      #  name: mysql-db-admin-secret
      #  namespace: crossplane-system
      #type: Opaque
      #data:
      #  example-key: xyz     #encoded secret
      key: example-key                # Key within the Secret
      name: mysql-db-admin-secret     # Secret name
      namespace: crossplane-system    # Secret namespace
    adminUsername: myadminuser        # Administrative username