apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
resources:
- ../00-bootstrap/
- ../05-karpenter/
- ../06-karpenter-nodepools/
- ../10-crossplane/
- ../40-crossplane-providers/
- ../50-gatewayapi-crds/
- ../60-envoy-gateway/
- ../70-gateway-objects/
- 80-demo-stack-helm/