apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: api
        image: fra.ocir.io/frsxwtjslf35/demo-api:0.2.0
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: "redis.cache.svc.cluster.local:6379"
        - name: DB_NAME
          value: "main_db"