namespace: demo

image:
  repository: fra.ocir.io/frsxwtjslf35/demo-api
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 2

nodeSelector: {}
tolerations: []
affinity: {}

service:
  port: 8080

redis:
  host: "redis.demo.svc.cluster.local"
  port: 6379

mysql:
  host: "mysql.demo.svc.cluster.local"
  port: 3306
  database: "demo"

dbSecret:
  name: "mysql-admin-pass"

gateway:
  parentGatewayName: "eg"
  parentGatewayNamespace: "envoy-gateway-system"
  hostname: ""
  pathPrefix: "/"

connections:
  redis:
    secretName: demo-redis-conn
    hostKey: host
    portKey: port
    # alternatively, some providers publish "host" / "uri" etc.

  mysql:
    secretName: mysql-admin-pass
    hostSecret: demo-db-endpoint
    hostKey: endpoint
    portKey: port
    usernameKey: username
    passwordKey: password
    database: demo

