namespace: demo

image:
  repository: fra.ocir.io/frsxwtjslf35/demo-api
  tag: "0.2.3"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 80
  targetPort: 8080

# If you already have Secrets produced by Crossplane / KRO
connections:
  redis:
    secretName: demo-redis-conn
    # keys expected in the secret:
    hostKey: host
    portKey: port
    passwordKey: password

app:
  sessionTTL: "24h"
  maxBodyBytes: 1048576
  verboseByDefault: true
  requireJSON: false
  mysqlTable: requests

# schedule on “core” nodes or not (adjust to your model)
nodeSelector: {}
tolerations: []
affinity: {}
